---
swagger: '2.0'
info:
  version: 1.0.0
  title: Version Service
  description: RESTful service to manage information about internal services
schemes:
  - http
basePath: /service-registry/v1
consumes:
  - application/json
paths:
  /service:
    get:
        description: Retrieves a list of services
        responses:
          200:
            description: A list of services
            schema:
              type: array
              items:
                $ref: '#/definitions/Service'
          500:
            description: Server error
  /service/{id}:
    get:
      description: Retrieves a service
      parameters:
        - name: id
          in: path
          type: string
          required: true
      responses:
        200:
          description: A service
          schema:
            $ref: '#/definitions/Service'
        500:
          description: Server error
    put:
      description: Create a service
      parameters:
        - name: id
          in: path
          type: string
          required: true
        - name: service
          in: body
          required: true
          schema:
            $ref: "#/definitions/Service"
      responses:
        201:
          description: Service created
        400:
          description: Validation error
        500:
          description: Server error
definitions:
    Service:
      type: object
      properties:
        _id:
          type: string
        environments:
          type: array
          items:
            $ref: "#/definitions/environment"
        links:
          type: array
          items:
            $ref: "#/definitions/link"
        __v:
          type: string
    Environment:
      type: object
      properties:
        name:
          type: string
        baseUrl:
          type: string
    Link:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
