version: '2'
services:
  node:
    image: wealthwizardsengineering/ww-base-node:alpine-latest
    volumes:
      - .:/usr/src/app:z
    working_dir: /usr/src/app

  npm:
    extends:
      service: node
    entrypoint: npm

  unit-test:
    extends:
      service: npm
    command: run test:unit:report

  mongodb:
    image: mongo:3.4.1
    ports:
      - "27017:27017"
    container_name: mongodb

  component-test:
    extends:
      service: npm
    command: run test:component:report
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb://mongodb:27017/service_registry

  dev:
    extends:
      service: npm
    ports:
      - "3000:80"
    command: start
    environment:
      - PORT=80
      - MONGODB_URL=mongodb://mongodb:27017/service_registry
    depends_on:
      - mongodb
